### ISSUE TITLE
not working with import-js 3.1.0

### ISSUE THREAD

**Issue by linchen2chris** [Galooshi/emacs-import-js#26]
after I upgrade import-js to latest version (3.1.0), import-js always get "JSON readtable error".

**Comment by joeheyming** [comment]
I started debugging and found this issue:

import-data = /usr/local/lib/node_modules/import-js/build/Importer.js:118
        throw new Error(e);
        ^

Error: Error: The ’decorators’ plugin requires a ’decoratorsBeforeExport’ option, whose value must be a boolean.
    at new Importer (/usr/local/lib/node_modules/import-js/build/Importer.js:118:15)
    at Interface.<anonymous> (/usr/local/lib/node_modules/import-js/build/daemon.js:65:20)
    at emitOne (events.js:96:13)
    at Interface.emit (events.js:189:7)
    at Interface._onLine (readline.js:238:10)
    at Interface.<anonymous> (readline.js:375:12)
    at Array.forEach (native)
    at Interface._normalWrite (readline.js:374:11)
    at Socket.ondata (readline.js:98:10)
    at emitOne (events.js:96:13)

I googled the error message, but I think its something wrong with how babel is configured?

**Comment by jimmywongroo** [comment]
@trotzig Do you have any idea how to debug this?

**Comment by trotzig** [comment]
I've had very limited bandwidth the last couple of weeks, so I haven't been able to look into this issue. It's reported upstream as well, it might be good to keep the discussion there from now on: https://github.com/Galooshi/import-js/issues/515

Any help here is appreciated!

**Comment by kevinkehl** [comment]
Closing due to age - the latest import-js@5.0.0 and emacs-import-js@3.0.0 releases should now be stable.

**Comment by trotzig** [comment]
👋
